---
title: "p8105_hw5_yz4993"
author: "Yixin Zheng"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(broom)
```

#Problem 1
```{r p1_create function}
simulate_birthday <- function(n) {
  birthdays <- sample(1:365, n, replace = TRUE) # assign random birthdays
  any(duplicated(birthdays)) # check for duplicate birthdays
  }
```

```{r p1_parameters}
set.seed(42)
sizes <- 2:50
num_of_times_1 <- 10000
```

```{r p1_simulation}
p1_results <- tibble(
  group_size = sizes,
  probability = map_dbl(sizes, 
                        function(n) {
                          mean(replicate(num_of_times_1,
                                         simulate_birthday(n)))
                          })
  )

# another method:
# sim_results_df <- expand_grid(group_size = 2:50, iter = 1:10000) |> mutate(has_shared_birthday = map_lgl(group_size, simulate_birthday)) |> group_by(group_size) |> summarize(probability = mean(has_shared_birthday), .groups = "drop")
```

```{r p1_plot}
p1_results %>%
  ggplot(aes(x = group_size, y = probability)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Probability of Shared Birthday in a Group",
    x = "Number of People in Group",
    y = "Probability"
    ) +
  theme_minimal(base_size = 14)
```

The plot above shows that as the group size increases, the probability of that at least two people in the group will share a birthday also increase. Around group size of 23,the probability exceeds 0.5(50%), and in group of 50 people, the probability is very close to 1(100%). Meaning

# Problem 2
```{r p2_parameter}
n <- 30
sigma <- 5
num_of_times_2 <- 5000
mu_values <- c(1, 2, 3, 4, 5, 6)
```

```{r p2_function}
t_test <- function(mu) {
  x <- rnorm(n, mean = mu, sd = sigma)
  t_test_result <- t.test(x, mu = 0)
  tidy(t_test_result) %>% 
    select(estimate, p.value)
}
```

```{r p2_mu0 simulation}
set.seed(42)
mu0_results <- tibble(
  iter = 1:num_of_times_2,
  test_result = map(iter, ~ t_test(mu = 0))
  ) %>%
  unnest(test_result)
```

```{r p2_mu0 power}
mu0_power <- mean(mu0_results$p.value < 0.05)
mu0_power
```


```{r p2_mu_values simulation}
mu_value_results <- expand_grid(
  mu = mu_values,
  iter = 1:num_of_times_2
  ) %>%
  mutate(
    test_result = map(mu, ~ t_test(.x))
    ) %>%
  unnest(test_result)
```

```{r p2_mu_values power}
mu_values_power <- mu_value_results %>%
  group_by(mu) %>%
  summarize(power = mean(p.value < 0.05), 
            .groups = "drop")
mu_values_power

# combine mu = 0 result with other power results
power_results <- bind_rows(
  tibble(mu = 0, power = mu0_power),
  mu_values_power
)
power_results
```

